// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvjYTa4_1gpEDuyBYCa6NgEQuu_Hrt7nw',
    appId: '1:646865117207:android:fd580e09980280c50e7c52',
    messagingSenderId: '646865117207',
    projectId: 'wechat-5c17e',
    storageBucket: 'wechat-5c17e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZkFa5aJZ4pESmRb50U7IK6WELvJ6rVOY',
    appId: '1:646865117207:ios:8d04b982aab8d0ed0e7c52',
    messagingSenderId: '646865117207',
    projectId: 'wechat-5c17e',
    storageBucket: 'wechat-5c17e.appspot.com',
    androidClientId: '646865117207-mpj4f4ga0m88iecroju450j7vhpafmj2.apps.googleusercontent.com',
    iosClientId: '646865117207-ask3glccu622imr6pjiiai0gbf02r5ak.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
